# Generated by Django 4.2.16 on 2024-10-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('theme', models.CharField(default='Природа', max_length=50)),
                ('atmosphere', models.CharField(choices=[('egyptian', 'Египетская'), ('jungle', 'Джунглей'), ('marine', 'Морская'), ('persian', 'Персидская'), ('japanese', 'Японская'), ('russian', 'Российская')], max_length=50)),
                ('hashtags', models.CharField(blank=True, max_length=255)),
                ('author_name', models.CharField(max_length=100)),
                ('work_title', models.CharField(max_length=100)),
                ('work_type', models.CharField(choices=[('Обложка', 'Обложка'), ('Трек', 'Трек')], max_length=50)),
            ],
        ),
    ]
